// pages/home/world/world.js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    entranceUnions:[{
      name:"排行榜",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试2",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试3",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试4",
      icon:"../../images/testicon.png",
      link:"",
    }],
    cardInfo:[{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      name:"排行榜",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试2",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试3",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试4",
      icon:"../../images/testicon.png",
      link:"",
    }],
    cardInfo:[{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      name:"排行榜",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试2",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试3",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试4",
      icon:"../../images/testicon.png",
      link:"",
    }],
    cardInfo:[{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      name:"排行榜",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试2",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试3",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试4",
      icon:"../../images/testicon.png",
      link:"",
    }],
    cardInfo:[{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      name:"排行榜",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试2",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试3",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试4",
      icon:"../../images/testicon.png",
      link:"",
    }],
    cardInfo:[{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      name:"排行榜",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试2",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试3",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试4",
      icon:"../../images/testicon.png",
      link:"",
    }],
    cardInfo:[{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      name:"排行榜",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试2",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试3",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试4",
      icon:"../../images/testicon.png",
      link:"",
    }],
    cardInfo:[{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      name:"排行榜",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试2",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试3",
      icon:"../../images/testicon.png",
      link:"",
    },{
      name:"测试4",
      icon:"../../images/testicon.png",
      link:"",
    }],
    cardInfo:[{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/zeen-chin-005.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    },{
      cmtInfo:{
        icon:"../../images/test_community_icon.png",
        name:"B02",
        members:"1328",
      },
      user:{
        name:"匿名用户",
        identity:"anons",
      },
      img:["../../images/demoImg01.jpeg"],
      text:"这个塞尔达画得可太彳亍了，爱了家人们",
      likes:"312",
      follows:"27",
      comments:"36",
    }]
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {

  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function () {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function () {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function () {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function () {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function () {

  }
})